---
- hosts: all
  gather_facts: no
  become_user: postgres
  become: true
  tasks:
    - name: Create database
      postgresql_db:
        name: "icinga2"
        login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"
    - name: "Create functions (loop)"
      postgresql_query:
        db: "icinga2"
        query: "{{ item }}"
        login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"
      with_items:
        - "DROP FUNCTION IF EXISTS from_unixtime(bigint);"
        - >
          CREATE FUNCTION from_unixtime(bigint) RETURNS timestamp AS $$
          SELECT to_timestamp($1) AT TIME ZONE 'UTC' AS result
          $$ LANGUAGE sql;
        - "DROP FUNCTION IF EXISTS unix_timestamp(timestamp WITH TIME ZONE);"
        - >
          CREATE OR REPLACE FUNCTION unix_timestamp(timestamp) RETURNS bigint AS '
            SELECT CAST(EXTRACT(EPOCH FROM $1) AS bigint) AS result;
          ' LANGUAGE sql;
        - >
          CREATE OR REPLACE FUNCTION updatedbversion(version_i TEXT) RETURNS void AS $$
          BEGIN
          IF EXISTS( SELECT * FROM icinga_dbversion WHERE name='idoutils')
          THEN
          UPDATE icinga_dbversion
          SET version=version_i, modify_time=NOW()
          WHERE name='idoutils';
          ELSE
          INSERT INTO icinga_dbversion (dbversion_id, name, version, create_time, modify_time) VALUES ('1', 'idoutils', version_i, NOW(), NOW());
          END IF;
          RETURN;
          END;
          $$ LANGUAGE plpgsql;
    - name: "Create table #1"
      postgresql_table:
        name: icinga_acknowledgements
        columns:
          - 'acknowledgement_id bigserial'
          - 'instance_id bigint default 0'
          - 'entry_time timestamp'
          - 'entry_time_usec INTEGER  default 0'
          - 'acknowledgement_type INTEGER  default 0'
          - 'object_id bigint default 0'
          - 'state INTEGER  default 0'
          - "author_name TEXT  default ''"
          - "comment_data TEXT  default ''"
          - 'is_sticky INTEGER  default 0'
          - 'persistent_comment INTEGER  default 0'
          - 'notify_contacts INTEGER  default 0'
          - 'end_time timestamp'
          - 'CONSTRAINT PK_acknowledgement_id PRIMARY KEY (acknowledgement_id)'
        login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"
    - name: "Create table #2"
      postgresql_table:
        name: icinga_commands
        columns:
          - 'command_id bigserial'
          - 'instance_id bigint default 0'
          - 'config_type INTEGER  default 0'
          - 'object_id bigint default 0'
          - "command_line TEXT  default ''"
          - 'config_hash varchar(64) DEFAULT NULL'
          - 'CONSTRAINT PK_command_id PRIMARY KEY (command_id)'
          - 'CONSTRAINT UQ_commands UNIQUE (instance_id,object_id,config_type)'
        login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"
    - name: "Create user 1"
      postgresql_user:
        name: testuser
        db: icinga2
        priv: ALL
        role_attr_flags: superuser
        login_unix_socket: "/var/run/postgresql/.s.PGSQL.5432"